-- FIX ARTICLES & PLATFORMS SCHEMA
-- RUN THIS IN SUPABASE SQL EDITOR

-- 1. Create Articles Table
CREATE TABLE IF NOT EXISTS public.articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE,
    content TEXT,
    thumbnail TEXT,
    author TEXT,
    tags TEXT[],
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Casinos Table (if missing, though likely exists)
CREATE TABLE IF NOT EXISTS public.casinos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE,
    rating NUMERIC DEFAULT 0,
    votes INT DEFAULT 0,
    affiliate_link TEXT,
    logo TEXT,
    description TEXT,
    short_description TEXT,
    images TEXT[],
    bonuses JSONB DEFAULT '{}',
    features JSONB DEFAULT '{}',
    payment_methods JSONB DEFAULT '{}',
    software_providers JSONB DEFAULT '{}',
    visibility_countries TEXT[] DEFAULT ARRAY['global'],
    category TEXT DEFAULT 'Casino',
    tags TEXT[],
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Shortlinks (if missing)
CREATE TABLE IF NOT EXISTS public.shortlinks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    target_url TEXT NOT NULL,
    clicks INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Country Rules (if missing, for banned regions)
CREATE TABLE IF NOT EXISTS public.country_rules (
    country_code TEXT PRIMARY KEY,
    status TEXT DEFAULT 'allowed' -- 'allowed' or 'blocked'
);

NOTIFY pgrst, 'reload schema';
