-- CRITICAL FIXES FOR DATABASE SCHEMA
-- RUN THIS IN SUPABASE SQL EDITOR

-- 1. Fix 'users' table ID auto-generation and missing columns
-- We assume 'id' should be an auto-incrementing integer (BigInt) for this app design, 
-- or we fix it to allow NULLs if it's meant to be managed differently (but usually PK needs value).
-- If 'id' is already there, we ensure it has a default.

DO $$ 
BEGIN 
    -- Make 'id' auto-increment if it isn't already (for Postgres 10+)
    -- This handles the "null value in column id" error
    IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'id' AND column_default IS NULL) THEN
        ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- Add Status and Tracking Columns (Fixes PGRST204)
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS first_ip TEXT,
ADD COLUMN IF NOT EXISTS last_ip TEXT,
ADD COLUMN IF NOT EXISTS country_code TEXT,
ADD COLUMN IF NOT EXISTS language TEXT,
ADD COLUMN IF NOT EXISTS user_id UUID DEFAULT gen_random_uuid(),
ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS verification_code TEXT,
ADD COLUMN IF NOT EXISTS verification_expires TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS avatar TEXT,
ADD COLUMN IF NOT EXISTS google_id TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- 2. Fix 'analytics' table (Fixes 42703 column analytics.created_at does not exist)
CREATE TABLE IF NOT EXISTS public.analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT,
    country TEXT,
    page_url TEXT,
    user_agent TEXT,
    referrer TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure created_at exists if table already existed
ALTER TABLE public.analytics ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- 3. Fix 'active_sessions' table
CREATE TABLE IF NOT EXISTS public.active_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT UNIQUE,
    country TEXT,
    last_seen TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Fix 'subscribers' table (Just in case)
CREATE TABLE IF NOT EXISTS public.subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    status TEXT DEFAULT 'active',
    subscribed_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Force Schema Cache Reload (Frontend might need this, but restarting server helps)
NOTIFY pgrst, 'reload schema';
