-- FINAL CORRECTED SCHEMA FIX
-- RUN THIS IN SUPABASE SQL EDITOR

-- 1. Fix 'users' table ID (Assuming it is UUID based on the error)
-- This fixes "null value in column id" by telling DB to auto-generate the UUID
ALTER TABLE public.users ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- 2. Ensure Schema Compatibility (Add missing columns if they don't exist)
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS first_ip TEXT,
ADD COLUMN IF NOT EXISTS last_ip TEXT,
ADD COLUMN IF NOT EXISTS country_code TEXT,
ADD COLUMN IF NOT EXISTS language TEXT,
ADD COLUMN IF NOT EXISTS user_id UUID DEFAULT gen_random_uuid(), -- Legacy/Duplicate ID support
ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS verification_code TEXT,
ADD COLUMN IF NOT EXISTS verification_expires TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS avatar TEXT,
ADD COLUMN IF NOT EXISTS google_id TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- 3. Fix Analytics
CREATE TABLE IF NOT EXISTS public.analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT,
    country TEXT,
    page_url TEXT,
    user_agent TEXT,
    referrer TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.analytics ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- 4. Reload Schema
NOTIFY pgrst, 'reload schema';
